// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pohtomqnjpnuvuccorov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvaHRvbXFuanBudXZ1Y2Nvcm92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NDUyNzEsImV4cCI6MjA3MjQyMTI3MX0.fdR-NHVyM1dntPFjemd99iTpCNEK1tL5V2QX_LLwS24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});